/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trntravel;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    public Connection conn;
    public Statement cn;
    Statement statement;
    ResultSet resultSet;
    public static int kondisiLogin=3;
    public static String userLogin="Tidak Terdeteksi";

            
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public void login() {
        try {
            Connection cn = koneksi.getKoneksi();
            Statement s = cn.createStatement();
            String sql = "Select * from admin where username='" + taUsername1.getText() + "' and password='" + taPassword1.getText() + "'";
            ResultSet rs = s.executeQuery(sql);
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Selamat Datang "+ taUsername1.getText()+"!" );
                new Home().show();
            }else{
                JOptionPane.showMessageDialog(null, "Username atau Password Salah !");
            }          
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taPassword1 = new javax.swing.JPasswordField();
        taUsername1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taPassword1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        taPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(taPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 30));

        taUsername1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        taUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taUsername1ActionPerformed(evt);
            }
        });
        getContentPane().add(taUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 140, 30));

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login Form");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 101, 49));

        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 105, 49));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Image00003.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/647802-rail-road-in-field.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taPassword1ActionPerformed

    private void taUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taUsername1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Reset Button
        taUsername1.setText("");
        taPassword1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Exit Button
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Login Button
        
        login();
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField taPassword1;
    private javax.swing.JTextField taUsername1;
    // End of variables declaration//GEN-END:variables
}
